[package]
categories.workspace = true
description = "Geometry algorithms: sampling, extrema, conversion"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "brepkit-geometry"
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
brepkit-math.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
