[package]
categories.workspace = true
description = "Walking-based fillet and chamfer engine for brepkit"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "brepkit-blend"
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
brepkit-math.workspace = true
brepkit-topology.workspace = true

log.workspace = true
thiserror.workspace = true

[dev-dependencies]
brepkit-topology = {workspace = true, features = ["test-utils"]}

[lints]
workspace = true
